### ISSUE TITLE
convertRdfFile.sh: errors during conversion to "json-ld"

### ISSUE THREAD

**Issue by przemekgradzki** [edmcouncil/ontology-publisher#15]
[Jenkins/fibo/master/#179, stage:"Build Ontology"](https://jenkins.edmcouncil.org/blue/rest/organizations/jenkins/pipelines/fibo/branches/master/runs/179/nodes/73/log/) lines 1638-1650:

`ERROR: in function convertRdfFileTo() at .(convertRdfFile.sh:85): ^[[38;5;208mFound errors during conversion ofSEC/Equities/EquityCFIClassificationIndividuals.rdf to "json-ld":^[[0m
(ERROR) SesameRdfFormatter: stopped by unexpected exception:
(ERROR) RDFHandlerException: unable to generate/write RDF output
(ERROR) org.eclipse.rdf4j.rio.RDFHandlerException: unable to generate/write RDF output
        at org.edmcouncil.rdf_toolkit.SesameSortedJsonLdWriter.endRDF(SesameSortedJsonLdWriter.java:143)
        at org.eclipse.rdf4j.rio.Rio.write(Rio.java:427)
        at org.edmcouncil.rdf_toolkit.SesameRdfFormatter.run(SesameRdfFormatter.java:394)
        at org.edmcouncil.rdf_toolkit.SesameRdfFormatter.main(SesameRdfFormatter.java:110)
Caused by: org.eclipse.rdf4j.rio.RDFHandlerException: unable to generate/write RDF output
        at org.edmcouncil.rdf_toolkit.SesameSortedRDFWriter.endRDF(SesameSortedRDFWriter.java:1347)
        at org.edmcouncil.rdf_toolkit.SesameSortedJsonLdWriter.endRDF(SesameSortedJsonLdWriter.java:141)
        ... 3 more
Caused by: java.lang.ClassCastException: class org.eclipse.rdf4j.model.impl.SimpleBNode cannot be cast to class org.eclipse.rdf4j.model.IRI (org.eclipse.rdf4j.model.impl.SimpleBNode and org.eclipse.rdf4j.model.IRI are in unnamed module of loader 'app')`

[rdf-toolkit](https://github.com/edmcouncil/rdf-toolkit/) tool (downloaded from [here](https://jenkins.edmcouncil.org/view/rdf-toolkit/job/rdf-toolkit-build/lastSuccessfulBuild/artifact/target/scala-2.12/rdf-toolkit.jar)) throws an error while converting [SEC/Equities/EquityCFIClassificationIndividuals.rdf](https://github.com/edmcouncil/fibo/blob/master/SEC/Equities/EquityCFIClassificationIndividuals.rdf) file to "json-ld" serialization.

Steps to reproduce error:

* install [AdoptOpenJDK 11](https://adoptopenjdk.net/installation.html?variant=openjdk11&jvmVariant=hotspot#) or greater
* download [javax.xml.bind.jar](https://github.com/edmcouncil/ontology-publisher/raw/master/publisher/lib/javax.xml.bind.jar) and [rdf-toolkit.jar](https://github.com/edmcouncil/ontology-publisher/raw/master/publisher/lib/rdf-toolkit.jar)
* download ontology [SEC/Equities/EquityCFIClassificationIndividuals.rdf](https://raw.githubusercontent.com/edmcouncil/fibo/master/SEC/Equities/EquityCFIClassificationIndividuals.rdf)
* run:
`java --add-opens java.base/java.lang=ALL-UNNAMED \`
`-Xmx1G -Xms1G -Dfile.encoding=UTF-8 \`
`-cp "javax.xml.bind.jar:rdf-toolkit.jar" org.edmcouncil.rdf_toolkit.SesameRdfFormatter \`
`--source "EquityCFIClassificationIndividuals.rdf" --source-format "rdf-xml" \`
`--target "EquityCFIClassificationIndividuals.jsonld" --target-format "json-ld" \`
`--inline-blank-nodes --infer-base-iri --use-dtd-subset`

Converting other files (e.g. [SEC/Equities/EquitiesExampleIndividuals.rdf](https://raw.githubusercontent.com/edmcouncil/fibo/master/SEC/Equities/EquitiesExampleIndividuals.rdf)) works good

**Comment by przemekgradzki** [comment]
[riot](https://jena.apache.org/documentation/io/) tool converts the file without errors:

`riot --out=jsonld EquityCFIClassificationIndividuals.rdf`

Tested on [Apache Jena v3.16.0](http://archive.apache.org/dist/jena/binaries/apache-jena-3.16.0.tar.gz)

**Comment by mereolog** [comment]
I think the reason why it crashes is that it expects that each triple that has rdf:type as the predicate also has an IRI as an object - see [lines 387-288 in SesameSortedJsonLdWriter](https://github.com/edmcouncil/rdf-toolkit/blob/54a12f12a3d799d068ed148dc37031255645f252/src/main/java/org/edmcouncil/rdf_toolkit/SesameSortedJsonLdWriter.java#L387-L388):
```
if (isRdfTypePredicate) {
   writeObject(out, (IRI)value, isRdfTypePredicate);
```
Now EquityCFIClassificationIndividuals.rdf has triples that do not satisfy this condition, e.g., 
```
<owl:NamedIndividual rdf:about="&fibo-sec-eq-10962;ESVUFR">
		...
		<rdf:type>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&lcc-cr;classifies"/>
				<owl:someValuesFrom>
					<owl:Class>
						<owl:intersectionOf rdf:parseType="Collection">
							<rdf:Description rdf:about="&fibo-sec-eq-eq;CommonVotingUnrestrictedFullyPaidRegisteredShare">
							</rdf:Description>
							<owl:Restriction>
								<owl:onProperty rdf:resource="&fibo-sec-sec-iss;isIssuedInForm"/>
								<owl:hasValue rdf:resource="&fibo-sec-sec-iss;RegisteredForm"/>
							</owl:Restriction>
						</owl:intersectionOf>
					</owl:Class>
				</owl:someValuesFrom>
			</owl:Restriction>
		</rdf:type>
```
I.e., EquityCFIClassificationIndividuals.rdf classifies some resources as instances of OWL restrictions.
Formally, it is correct, i.e., RDF(S) allows for such triples.

Still, if we were to take up an effort to refactor the code so that it can handles such cases, the amount of work would be considerable because we would have to deal with each type of OWL restrictions separately and sometimes recursively.

Given the fact that riot serialises them seamlessly, I would recommend using it instead.

Having said that let me mention that Protege does not open the json-ld file produced by riot - it spawns this error:
`An error occurred whilst loading the ontology at *** Cause: Not a valid (absolute) URI: @graph`
Indeed the json-ld file starts like this:
```
{
  "@graph" : [ {
    "@id" : "_:b0",
    "@type" : "owl:Restriction",
    "hasValue" : "fibo-sec-sec-iss:RegisteredForm",
    ....
```
This looks like a bug in Protege - see: https://github.com/protegeproject/protege/issues/866.

However, @przemekgradzki, can we run riot with the option where '@graph' is replaced with the IRI of the ontology?
That is, can we get a json that starts like the one below?
```
{
  "@https://spec.edmcouncil.org/fibo/ontology/SEC/Equities/EquityCFIClassificationIndividuals/" : [ {
    "@id" : "_:b0",
    "@type" : "owl:Restriction",
    "hasValue" : "fibo-sec-sec-iss:RegisteredForm",
    ....
```

**Comment by przemekgradzki** [comment]
@mereolog is '**@graph**' is the only problem? We can apply a temporary workaround:

`sed 's#@graph#@https://spec.edmcouncil.org/fibo/ontology/SEC/Equities/EquityCFIClassificationIndividuals/#g' EquityCFIClassificationIndividuals.jsonld`

This can be done automatically for all ontology files

**Comment by mereolog** [comment]
Yes, as of now it is the only issue, well sort of, as Protege seems to be bugged.
Anyway, it would be better to have it fixed so that the users can open theses jsons in Protege.
Note that each json should have its own replacement - this can be got from the concatenation of 'https://spec.edmcouncil.org/fibo/ontology/' and the ontology relative location, e.g., 'SEC/Equities/EquityCFIClassificationIndividuals.rdf'

**Comment by przemekgradzki** [comment]
pull request: [INFRA-496 convertRdfFile.sh: errors during conversion to "json-ld" #17](https://github.com/edmcouncil/ontology-publisher/pull/17)
